"""add problem_type to feedback

Revision ID: 14acaa779a36
Revises: 479e530a9bd0
Create Date: 2026-04-29 18:33:04.678218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14acaa779a36'
down_revision: Union[str, Sequence[str], None] = '479e530a9bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('problem_type', sa.String(length=50), nullable=True))
    op.alter_column('feedback', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_api_id', 'feedback', ['api_id'], unique=False)
    op.drop_constraint(op.f('feedback_api_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'apis', ['api_id'], ['api_id'])
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_api_id_fkey'), 'feedback', 'apis', ['api_id'], ['api_id'], ondelete='SET NULL')
    op.drop_index('idx_api_id', table_name='feedback')
    op.alter_column('feedback', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('feedback', 'problem_type')
    # ### end Alembic commands ###
