"""make feedback api_id nullable

Revision ID: a0d76060f94b
Revises: 
Create Date: 2026-03-13 01:09:04.944150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d76060f94b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "domains",
        sa.Column("domain_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("domain_name", sa.String(), nullable=False, unique=True),
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("role_name", sa.String(length=50), nullable=False),
    )
    op.create_table(
        "companies",
        sa.Column("company_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("company_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("domain_id", sa.Integer(), sa.ForeignKey("domains.domain_id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.company_id"), nullable=False),
        sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.role_id"), nullable=False),
        sa.Column("f_name", sa.String(length=50), nullable=False),
        sa.Column("l_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "apis",
        sa.Column("api_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.company_id"), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(length=50), nullable=False),
        sa.Column("api_base_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "feedback_categories",
        sa.Column("category_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("domain_id", sa.Integer(), sa.ForeignKey("domains.domain_id"), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
    )
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.company_id"), nullable=False),
        sa.Column("api_id", sa.Integer(), sa.ForeignKey("apis.api_id"), nullable=True),
        sa.Column("category_id", sa.Integer(), sa.ForeignKey("feedback_categories.category_id"), nullable=True),
        sa.Column("customer_name", sa.String(length=100), nullable=True),
        sa.Column("feedback_context", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("sentiment", sa.String(length=20), nullable=True),
        sa.Column("emotion", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("ml_processed_at", sa.DateTime(timezone=True), nullable=True),
    )

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO domains (domain_id, domain_name) VALUES (:id, :name)"
        ),
        [{"id": 1, "name": "Food"}],
    )
    bind.execute(
        sa.text(
            "INSERT INTO roles (role_id, role_name) VALUES (:id, :name)"
        ),
        [
            {"id": 1, "name": "Manager"},
            {"id": 2, "name": "Customer service supervisor"},
            {"id": 3, "name": "Website configurator"},
        ],
    )

    op.alter_column('feedback', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles WHERE role_id IN (1, 2, 3)")
    op.execute("DELETE FROM domains WHERE domain_id = 1")
    op.alter_column('feedback', 'api_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
